### ISSUE TITLE
Book mistitled in cover image and elsewhere

### ISSUE THREAD

**Issue by jbullock35** [standardebooks/george-bernard-shaw_you-never-can-tell#1]
According to [Wikipedia](https://en.wikipedia.org/wiki/You_Never_Can_Tell_(play)), [Project Gutenberg](https://www.gutenberg.org/ebooks/2175), and other sources, this play's title is _You Never Can Tell._ If they're right, the play is mistitled at https://standardebooks.org/ebooks/george-bernard-shaw/you-can-never-tell. The cover image there, the URL, and the name of this repository may all bear changing.

**Comment by acabal** [comment]
Oops! Thanks, this should be fixed now.
